import json
import logging
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

import boto3

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

SLA_DEFINITIONS: List[Dict[str, Any]] = [
    {
        "sla_id": "SLA001",
        "name": "daily_ingestion",
        "target_hour": 7,
        "description": "Data ingested by 7 AM EST",
    },
    {
        "sla_id": "SLA002",
        "name": "anomaly_detection",
        "target_hour": 8,
        "description": "Anomalies detected by 8 AM EST",
    },
    {
        "sla_id": "SLA003",
        "name": "predictions_ready",
        "target_hour": 9,
        "description": "Predictions ready by 9 AM EST",
    },
    {
        "sla_id": "SLA004",
        "name": "insights_generated",
        "target_hour": 10,
        "description": "Insights generated by 10 AM EST",
    },
    {
        "sla_id": "SLA005",
        "name": "snowflake_sync",
        "target_hour": 11,
        "description": "Snowflake synced by 11 AM EST",
    },
    {
        "sla_id": "SLA006",
        "name": "dashboard_updated",
        "target_hour": 11,
        "description": "Dashboard updated by 11 AM EST",
    },
]

_SLA_MAP: Dict[str, Dict[str, Any]] = {str(s["sla_id"]): s for s in SLA_DEFINITIONS}


def record_sla_completion(
    sla_id: str,
    completed_at: str,
    bucket: str,
    date: str,
) -> bool:
    sla_def = _SLA_MAP.get(str(sla_id), {})
    target_hour = int(str(sla_def.get("target_hour", 23)))
    try:
        completed_hour = datetime.fromisoformat(completed_at).hour
    except Exception:
        completed_hour = 23

    met = completed_hour <= target_hour
    record: Dict[str, Any] = {
        "sla_id": sla_id,
        "completed_at": completed_at,
        "target_hour": target_hour,
        "met": met,
    }
    dt = datetime.strptime(date, "%Y-%m-%d")
    key = f"sla/completions/{dt.year}/{dt.month:02d}/{dt.day:02d}/{sla_id}.json"
    try:
        s3 = boto3.client("s3")
        s3.put_object(Bucket=bucket, Key=key, Body=json.dumps(record))
        status = "MET" if met else "MISSED"
        logger.info("SLA %s %s: completed at hour %d, target hour %d", sla_id, status,
                    completed_hour, target_hour)
        return True
    except Exception as e:
        logger.error("Failed to record SLA completion %s: %s", sla_id, e)
        return False


def generate_sla_report(bucket: str, date: str) -> Dict[str, Any]:
    s3 = boto3.client("s3")
    dt = datetime.strptime(date, "%Y-%m-%d")
    by_sla: Dict[str, Any] = {}
    met_count = 0
    total_checked = 0

    for sla_def in SLA_DEFINITIONS:
        sla_id = str(sla_def["sla_id"])
        key = f"sla/completions/{dt.year}/{dt.month:02d}/{dt.day:02d}/{sla_id}.json"
        try:
            obj = s3.get_object(Bucket=bucket, Key=key)
            record = json.loads(obj["Body"].read().decode("utf-8"))
            met = bool(record.get("met", False))
            by_sla[sla_id] = {
                "name": str(sla_def["name"]),
                "met": met,
                "completed_at": str(record.get("completed_at", "")),
                "target_hour": int(str(sla_def["target_hour"])),
            }
            if met:
                met_count += 1
            total_checked += 1
        except Exception:
            by_sla[sla_id] = {
                "name": str(sla_def["name"]),
                "met": False,
                "completed_at": "",
                "target_hour": int(str(sla_def["target_hour"])),
            }

    total = len(SLA_DEFINITIONS)
    compliance_pct = round((met_count / total) * 100, 1) if total > 0 else 0.0
    report: Dict[str, Any] = {
        "date": date,
        "compliance_pct": compliance_pct,
        "met_count": met_count,
        "missed_count": total - met_count,
        "by_sla": by_sla,
    }

    report_key = f"sla/reports/{dt.year}/{dt.month:02d}/{dt.day:02d}/report.json"
    try:
        s3.put_object(Bucket=bucket, Key=report_key, Body=json.dumps(report))
    except Exception as e:
        logger.error("Failed to save SLA report: %s", e)

    logger.info("SLA compliance for %s: %.1f%% (%d/%d met)", date, compliance_pct, met_count,
                total)
    return report


def get_sla_trend(bucket: str, days: int = 30) -> Dict[str, Any]:
    s3 = boto3.client("s3")
    daily: List[Dict[str, Any]] = []
    today = datetime.utcnow()

    for i in range(days):
        dt = today - timedelta(days=i)
        date_str = dt.strftime("%Y-%m-%d")
        key = f"sla/reports/{dt.year}/{dt.month:02d}/{dt.day:02d}/report.json"
        try:
            obj = s3.get_object(Bucket=bucket, Key=key)
            record = json.loads(obj["Body"].read().decode("utf-8"))
            daily.append({
                "date": date_str,
                "compliance_pct": float(str(record.get("compliance_pct", 0.0))),
            })
        except Exception:
            pass

    avg_compliance = (
        round(sum(float(str(d["compliance_pct"])) for d in daily) / len(daily), 1)
        if daily
        else 0.0
    )

    trend = "stable"
    if len(daily) >= 2:
        recent = float(str(daily[0]["compliance_pct"]))
        older = float(str(daily[-1]["compliance_pct"]))
        if recent > older + 5:
            trend = "improving"
        elif recent < older - 5:
            trend = "declining"

    result: Dict[str, Any] = {
        "avg_compliance_pct": avg_compliance,
        "trend": trend,
        "daily": daily,
    }
    logger.info("SLA trend over %d days: avg=%.1f%%, trend=%s", len(daily), avg_compliance, trend)
    return result


def run_sla_reporting(bucket: str) -> Dict[str, Any]:
    date = datetime.utcnow().strftime("%Y-%m-%d")
    report = generate_sla_report(bucket, date)
    trend = get_sla_trend(bucket)
    combined: Dict[str, Any] = {**report, "trend": trend}
    logger.info("SLA Reporting Complete")
    return combined


if __name__ == "__main__":
    pass
